myfile <- list.files()
txtfile <- myfile[grep(myfile, pattern = ".ctss$")]
library(CAGEr)

myCAGEset <- new("CAGEset", genomeName = "NULL", inputFiles = txtfile, inputFilesType = "ctss",sampleLabels = c("A15_30_1_A", "A15_30_1_T","A15_30_2_A", "A15_30_2_T","A40_1_A","A40_1_T", "A40_2_A", "A40_2_T","A10_1_A","A10_1_T","A10_2_A","A10_2_T","APO_1_A","APO_1_T","APO_2_A","APO_2_T"))
getCTSS(myCAGEset)
ctss <- CTSStagCount(myCAGEset)
sampleLabels(myCAGEset)
pdf("plotReverseCumulatives.pdf")
plotReverseCumulatives(myCAGEset, fitInRange = c(5, 1000), onePlot = TRUE)
dev.off()

normalizeTagCount(myCAGEset, method = "powerLaw",fitInRange = c(5, 1000), alpha = 1.05, T = 1*10^7)
clusterCTSS(object = myCAGEset, threshold = 0.5, thresholdIsTpm = TRUE, nrPassThreshold = 1, method = "distclu", maxDist = 24, removeSingletons = TRUE, keepSingletonsAbove = 3)
write.table(tagClusters(myCAGEset, sample = "A15_30_1_A"),file = "A15_30_1_A.csv",sep = "\t")
write.table(tagClusters(myCAGEset, sample = "A15_30_1_T"),file = "A15_30_1_T.csv",sep = "\t")
write.table(tagClusters(myCAGEset, sample = "A15_30_2_A"),file = "A15_30_2_A.csv",sep = "\t")
write.table(tagClusters(myCAGEset, sample = "A15_30_2_T"),file = "A15_30_2_T.csv",sep = "\t")
write.table(tagClusters(myCAGEset, sample = "A40_1_A"),file = "A40_1_A.csv",sep = "\t")
write.table(tagClusters(myCAGEset, sample = "A40_1_T"),file = "A40_1_T.csv",sep = "\t")
write.table(tagClusters(myCAGEset, sample = "A40_2_A"),file = "A40_2_A.csv",sep = "\t")
write.table(tagClusters(myCAGEset, sample = "A40_2_T"),file = "A40_2_T.csv",sep = "\t")
write.table(tagClusters(myCAGEset, sample = "A10_1_A"),file = "A10_1_A.csv",sep = "\t")
write.table(tagClusters(myCAGEset, sample = "A10_1_T"),file = "A10_1_T.csv",sep = "\t")
write.table(tagClusters(myCAGEset, sample = "A10_2_A"),file = "A10_2_A.csv",sep = "\t")
write.table(tagClusters(myCAGEset, sample = "A10_2_T"),file = "A10_2_T.csv",sep = "\t")
write.table(tagClusters(myCAGEset, sample = "APO_1_A"),file = "APO_1_A.csv",sep = "\t")
write.table(tagClusters(myCAGEset, sample = "APO_1_T"),file = "APO_1_T.csv",sep = "\t")
write.table(tagClusters(myCAGEset, sample = "APO_2_A"),file = "APO_2_A.csv",sep = "\t")
write.table(tagClusters(myCAGEset, sample = "APO_2_T"),file = "APO_2_T.csv",sep = "\t")
